<?php
/**
 * Static source: /404.html. Generated by make-wp-theme.js; copy changes belong in the static site first.
 */
$GLOBALS['svls_page_head'] = function () { ?>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Page Not Found | SVLS LABS</title>
<meta name="description" content="The page you asked for does not exist. Find SAP &amp; ERP, Cloud, Agentic &amp; Applied AI, Value Lens and Contact from here.">
<link rel="canonical" href="<?php echo esc_url( home_url( '/404.html' ) ); ?>">
<meta property="og:type" content="website">
<meta property="og:site_name" content="SVLS LABS">
<meta property="og:title" content="Page Not Found | SVLS LABS">
<meta property="og:description" content="The page you asked for does not exist. Find SAP &amp; ERP, Cloud, Agentic &amp; Applied AI, Value Lens and Contact from here.">
<meta property="og:url" content="<?php echo esc_url( home_url( '/404.html' ) ); ?>">
<meta property="og:image" content="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/og/og-404.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="SVLS LABS lockup and the page title on charcoal.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Page Not Found | SVLS LABS">
<meta name="twitter:description" content="The page you asked for does not exist. Find SAP &amp; ERP, Cloud, Agentic &amp; Applied AI, Value Lens and Contact from here.">
<meta name="twitter:image" content="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/og/og-404.png">
<meta name="theme-color" content="#0E1116" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0E1116" media="(prefers-color-scheme: dark)">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon.svg" type="image/svg+xml">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon-32.png" sizes="32x32" type="image/png">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon-16.png" sizes="16x16" type="image/png">
<link rel="apple-touch-icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/apple-touch-icon.png">
<link rel="manifest" href="<?php echo esc_url( get_template_directory_uri() ); ?>/site.webmanifest">
<script>(function(){var d=document.documentElement;d.classList.remove('no-js');try{var t=localStorage.getItem('svls-theme');if(t==='light'||t==='dark'){d.setAttribute('data-theme',t);}}catch(e){}})();</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preload" as="font" type="font/woff2" crossorigin href="https://fonts.gstatic.com/s/intertight/v9/NGSwv5HMAFg6IuGlBNMjxLsH8ag.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin href="https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7.woff2">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@800&display=swap">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/tokens.css">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/site.css">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/pages/legal.css">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/theme.css">
<script src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/js/site.js" defer></script>
<script src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/js/theme.js" defer></script>
<meta name="robots" content="noindex">
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "Page Not Found",
  "url": "https://svlslabs.com/404.html",
  "description": "The page you asked for does not exist. Find SAP & ERP, Cloud, Agentic & Applied AI, Value Lens and Contact from here.",
  "inLanguage": "en",
  "isPartOf": { "@type": "WebSite", "name": "SVLS LABS", "url": "https://svlslabs.com/" },
  "publisher": { "@type": "Organization", "name": "SVLS LABS", "legalName": "SVLS LABS LLP",
      "telephone": "+91 8500811119",
      "address": {"@type": "PostalAddress", "streetAddress": "4th Floor, Aparna Astute, Shaikpet, Door No. 8-1-299/103&104/AA/4F-2, Jubilee Hills", "addressLocality": "Hyderabad", "postalCode": "500008", "addressRegion": "Telangana", "addressCountry": "IN"}, "url": "https://svlslabs.com/", "foundingDate": "2020", "sameAs": ["https://www.linkedin.com/company/svlslabs/"] }
}
</script>
<?php };
get_header();
?>
<div class="sheet-backdrop" data-menu-backdrop hidden></div>
<div class="sheet" id="mobile-sheet" hidden>
  <nav aria-label="Menu">
    <ul class="sheet__list">
      <li>
        <span class="eyebrow sheet__group-label" id="sheet-services">Services</span>
        <ul class="sheet__sub" aria-labelledby="sheet-services">
          <li><a class="sheet__link" href="/services/sap/">SAP &amp; ERP</a></li>
          <li><a class="sheet__link" href="/services/cloud/">Cloud</a></li>
          <li><a class="sheet__link" href="/services/ai/">Agentic &amp; Applied AI</a></li>
        </ul>
      </li>
      <li>
        <span class="eyebrow sheet__group-label" id="sheet-products">Products</span>
        <ul class="sheet__sub" aria-labelledby="sheet-products">
          <li><a class="sheet__link" href="/products/value-lens/">Value Lens <span class="nav-beta">Private beta</span></a></li>
          <li><a class="sheet__link" href="/products/sap-intelligence-suite/">SAP Intelligence Suite</a></li>
        </ul>
      </li>
      <li><a class="sheet__link" href="/approach/">Approach</a></li>
      <li><a class="sheet__link" href="/about/">About</a></li>
      <li><a class="sheet__link" href="/contact/">Contact</a></li>
    </ul>
    <div class="sheet__actions">
      <a class="btn btn--primary" href="/contact/?intent=discovery">Book a discovery call</a>
      <a class="btn btn--secondary" href="/products/value-lens/#beta">Request Value Lens beta access</a>
    </div>
  </nav>
  <div class="sheet__theme" role="group" aria-label="Appearance">
    <span class="sheet__theme-label" aria-hidden="true">Appearance:</span>
    <button type="button" class="chip" data-theme-choice="system" aria-pressed="true">System</button>
    <button type="button" class="chip" data-theme-choice="light" aria-pressed="false">Light</button>
    <button type="button" class="chip" data-theme-choice="dark" aria-pressed="false">Dark</button>
  </div>
</div>
<main id="main" class="band-dark">

  <!-- 404: dark full page, grid texture, mark at 96px reversed -->
  <section class="section has-grid nf" aria-labelledby="nf-title">
    <div class="hero-art hero-art--lite" aria-hidden="true">
      <svg class="hero-art__mark" viewBox="0 0 64 64" focusable="false">
        <path d="M4 24V4h20v4H8v16z" fill="currentColor"/>
        <circle cx="32" cy="32" r="13.5" fill="none" stroke="currentColor" stroke-width="5"/>
        <path d="M60 40v20H40v-4h16V40z" fill="var(--svls-accent, #E4432B)"/>
      </svg>
    </div>
    <div class="container">
      <div class="section-mark"><span class="numeral">404</span><p class="eyebrow">Page not found</p></div>
      <svg class="nf__mark" viewBox="0 0 64 64" role="img" aria-labelledby="nf-mark-title" focusable="false">
        <title id="nf-mark-title">SVLS LABS</title>
        <path d="M4 24V4h20v4H8v16z" fill="currentColor"/>
        <circle cx="32" cy="32" r="13.5" fill="none" stroke="currentColor" stroke-width="5"/>
        <path d="M60 40v20H40v-4h16V40z" fill="var(--svls-accent, #E4432B)"/>
      </svg>
      <h1 id="nf-title">Nothing Here Has Been Measured.</h1>
      <p class="lead">The page you asked for does not exist, or has moved. These do:</p>
      <nav aria-label="Pages that exist">
        <ul class="hgrid hgrid--3 hgrid--bottom nf__links" role="list">
          <li>
            <a class="nf__link" href="/services/sap/">SAP &amp; ERP<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a>
            <span class="nf__desc">S/4HANA, RISE, BTP, Integration Suite, Clean Core</span>
          </li>
          <li>
            <a class="nf__link" href="/services/cloud/">Cloud<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a>
            <span class="nf__desc">SAP-to-cloud integration, migrations, cloud-native engineering</span>
          </li>
          <li>
            <a class="nf__link" href="/services/ai/">Agentic &amp; Applied AI<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a>
            <span class="nf__desc">Governed agents on SAP BTP, applied AI methods, AI-assisted engineering</span>
          </li>
          <li>
            <a class="nf__link" href="/products/value-lens/">Value Lens (private beta)<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a>
            <span class="nf__desc">Private beta on synthetic SAP-like data. Production SAP connector in development.</span>
          </li>
          <li>
            <a class="nf__link" href="/approach/">Approach<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a>
            <span class="nf__desc">Governed Delivery: four gates, artefacts per gate, Clean Core by default</span>
          </li>
          <li>
            <a class="nf__link" href="/contact/">Contact<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a>
            <span class="nf__desc">Talk to an architect. Replies within one business day.</span>
          </li>
        </ul>
      </nav>
      <div class="btn-row">
        <a class="btn btn--primary" href="/">Back to the homepage</a>
      </div>
    </div>
  </section>

</main>
<?php get_footer(); ?>
