<?php
/**
 * Template Name: Privacy Policy
 * Static source: /privacy/index.html. Generated by make-wp-theme.js; copy changes belong in the static site first.
 */
$GLOBALS['svls_page_head'] = function () { ?>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Privacy Policy | SVLS LABS</title>
<meta name="description" content="How SVLS LABS LLP collects and uses the details you send through svlslabs.com.">
<link rel="canonical" href="<?php echo esc_url( home_url( '/privacy/' ) ); ?>">
<meta property="og:type" content="website">
<meta property="og:site_name" content="SVLS LABS">
<meta property="og:title" content="Privacy Policy | SVLS LABS">
<meta property="og:description" content="How SVLS LABS LLP collects and uses the details you send through svlslabs.com.">
<meta property="og:url" content="<?php echo esc_url( home_url( '/privacy/' ) ); ?>">
<meta property="og:image" content="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/og/og-privacy.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="SVLS LABS lockup and the page title on charcoal.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Privacy Policy | SVLS LABS">
<meta name="twitter:description" content="How SVLS LABS LLP collects and uses the details you send through svlslabs.com.">
<meta name="twitter:image" content="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/og/og-privacy.png">
<meta name="theme-color" content="#0E1116" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0E1116" media="(prefers-color-scheme: dark)">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon.svg" type="image/svg+xml">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon-32.png" sizes="32x32" type="image/png">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon-16.png" sizes="16x16" type="image/png">
<link rel="apple-touch-icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/apple-touch-icon.png">
<link rel="manifest" href="<?php echo esc_url( get_template_directory_uri() ); ?>/site.webmanifest">
<script>(function(){var d=document.documentElement;d.classList.remove('no-js');try{var t=localStorage.getItem('svls-theme');if(t==='light'||t==='dark'){d.setAttribute('data-theme',t);}}catch(e){}})();</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preload" as="font" type="font/woff2" crossorigin href="https://fonts.gstatic.com/s/intertight/v9/NGSwv5HMAFg6IuGlBNMjxLsH8ag.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin href="https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7.woff2">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@800&display=swap">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/tokens.css?v=53ea99d0">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/site.css?v=421ce377">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/pages/legal.css?v=048296db">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/theme.css?v=95b1acdc">
<script src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/js/site.js?v=540ef525" defer></script>
<script src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/js/theme.js?v=1aa957a6" defer></script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "Privacy Policy",
  "url": "https://svlslabs.com/privacy/",
  "description": "How SVLS LABS LLP collects and uses the details you send through svlslabs.com.",
  "inLanguage": "en",
  "isPartOf": { "@type": "WebSite", "name": "SVLS LABS", "url": "https://svlslabs.com/" },
  "publisher": { "@type": "Organization", "name": "SVLS LABS", "legalName": "SVLS LABS LLP",
      "telephone": "+91 8500811119",
      "address": {"@type": "PostalAddress", "streetAddress": "4th Floor, Aparna Astute, Shaikpet, Door No. 8-1-299/103&104/AA/4F-2, Jubilee Hills", "addressLocality": "Hyderabad", "postalCode": "500008", "addressRegion": "Telangana", "addressCountry": "IN"}, "url": "https://svlslabs.com/", "foundingDate": "2020", "sameAs": ["https://www.linkedin.com/company/svlslabs/"] }
}
</script>
<?php };
get_header();
?>
<main id="main">

  <!-- 01 Hero (white, no grid) -->
  <section class="hero hero--plain hero--legal" aria-labelledby="hero-title">
    <div class="hero-art hero-art--lite" aria-hidden="true">
      <svg class="hero-art__mark" viewBox="0 0 64 64" focusable="false">
        <path d="M4 24V4h20v4H8v16z" fill="currentColor"/>
        <circle cx="32" cy="32" r="13.5" fill="none" stroke="currentColor" stroke-width="5"/>
        <path d="M60 40v20H40v-4h16V40z" fill="var(--svls-accent, #E4432B)"/>
      </svg>
    </div>
    <div class="container">
      <div class="section-mark"><span class="numeral">01</span><p class="eyebrow">Legal</p></div>
      <div class="grid hero__grid">
        <div class="hero__copy col-8">
          <h1 id="hero-title">Privacy Policy</h1>
          <p class="lead">How SVLS LABS LLP collects and uses the details you send through svlslabs.com.</p>
          <p class="small muted legal__updated">Last updated: 26 September 2026</p>
        </div>
        <ul class="microlabels hero__rows-a">
          <li>Legal entity · <span class="keep-case">SVLS LABS LLP</span></li>
          <li>Site · <span class="keep-case">svlslabs.com</span></li>
          <li>Status · In force</li>
        </ul>
      </div>
    </div>
  </section>

  <!-- 02 Sections (columns 1-7) and the review notice (9-12) -->
  <section class="section legal-body" id="sections" aria-labelledby="sections-title">
    <div class="container">
      <div class="section-mark mb-6"><span class="numeral">02</span><p class="eyebrow" id="sections-title">Privacy policy · 6 sections</p></div>
      <div class="grid legal__grid">
        <div class="col-7 prose legal__sections" data-reveal>
          <section class="legal__section" aria-labelledby="p-who">
            <span class="numeral">01</span>
            <h2 class="h3" id="p-who">Who We Are</h2>
            <p>svlslabs.com is published by SVLS LABS LLP. Established 2020.</p>
            <p>Registered office: 4th Floor, Aparna Astute, Shaikpet, Door No. 8-1-299/103&amp;104/AA/4F-2, Jubilee Hills, Hyderabad 500008, Telangana, India.</p>
            <p class="legal__note">Contact point for privacy questions: <a href="mailto:service@svlslabs.com">service@svlslabs.com</a>.</p>
          </section>
          <section class="legal__section" aria-labelledby="p-collect">
            <span class="numeral">02</span>
            <h2 class="h3" id="p-collect">What We Collect</h2>
            <p>The fields you send through the contact and beta forms: name, work email, company, role, what you are asking about and your message.</p>
            <p>Site analytics: this site uses Google Analytics, which sets cookies to measure visits and pages viewed. You can block these cookies in your browser settings without affecting the site.</p>
          </section>
          <section class="legal__section" aria-labelledby="p-use">
            <span class="numeral">03</span>
            <h2 class="h3" id="p-use">How We Use It</h2>
            <p>We use your details only to reply to your enquiry, to arrange the call or demo you asked for and to send you the document you requested. We do not sell your data, we do not use it for advertising and we do not add you to a mailing list unless you ask.</p>
          </section>
          <section class="legal__section" aria-labelledby="p-storage">
            <span class="numeral">04</span>
            <h2 class="h3" id="p-storage">Storage and Processors</h2>
            <p>Form submissions are delivered by email to service@svlslabs.com and kept in that mailbox for up to 12 months, then deleted unless an engagement follows. The site is hosted on GoDaddy Managed WordPress behind Cloudflare, which process technical data such as IP addresses and request logs to serve and protect the site. Google Analytics processes analytics data under Google's privacy terms.</p>
          </section>
          <section class="legal__section" aria-labelledby="p-rights">
            <span class="numeral">05</span>
            <h2 class="h3" id="p-rights">Your Rights</h2>
            <p>Under India's Digital Personal Data Protection Act, 2023 you may ask us to confirm what we hold about you, to correct it or to erase it, and you may withdraw consent at any time. Write to <a href="mailto:service@svlslabs.com">service@svlslabs.com</a>; we respond within 30 days. If you are outside India, the rights of your own jurisdiction apply and we honour the same requests.</p>
          </section>
          <section class="legal__section" aria-labelledby="p-contact">
            <span class="numeral">06</span>
            <h2 class="h3" id="p-contact">Contact</h2>
            <p>Privacy questions: <a href="mailto:service@svlslabs.com">service@svlslabs.com</a>, or the <a href="/contact/">contact form</a>.</p>

          </section>
        </div>
        <aside class="col-4 col-start-9 legal-aside" aria-label="About this page">
          <div class="notice">
            <p class="eyebrow">About this policy</p>
            <p>This policy was last updated on 26 September 2026. Questions go to service@svlslabs.com.</p>
          </div>
          <div class="legal-aside__block">
            <p class="eyebrow">Related</p>
            <ul class="legal-aside__links" role="list">
              <li><a class="arrow-link" href="/terms/">Terms of use<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></li>
              <li><a class="arrow-link" href="/approach/#security">Security and confidentiality<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></li>
              <li><a class="arrow-link" href="/contact/">Contact<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></li>
            </ul>
          </div>
        </aside>
      </div>
    </div>
  </section>

</main>
<?php get_footer(); ?>
