<?php
/**
 * Template Name: Contact SVLS LABS
 * Static source: /contact/index.html. Generated by make-wp-theme.js; copy changes belong in the static site first.
 */
$GLOBALS['svls_page_head'] = function () { ?>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Contact SVLS LABS | Book a Discovery Call</title>
<meta name="description" content="Book a discovery call with an SAP architect, request Value Lens beta access or ask about partner capacity. Replies within one business day.">
<link rel="canonical" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">
<meta property="og:type" content="website">
<meta property="og:site_name" content="SVLS LABS">
<meta property="og:title" content="Contact SVLS LABS | Book a Discovery Call">
<meta property="og:description" content="Book a discovery call with an SAP architect, request Value Lens beta access or ask about partner capacity. Replies within one business day.">
<meta property="og:url" content="<?php echo esc_url( home_url( '/contact/' ) ); ?>">
<meta property="og:image" content="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/og/og-contact.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="SVLS LABS lockup and the page title on charcoal.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Contact SVLS LABS | Book a Discovery Call">
<meta name="twitter:description" content="Book a discovery call with an SAP architect, request Value Lens beta access or ask about partner capacity. Replies within one business day.">
<meta name="twitter:image" content="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/og/og-contact.png">
<meta name="theme-color" content="#0E1116" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0E1116" media="(prefers-color-scheme: dark)">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon.svg" type="image/svg+xml">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon-32.png" sizes="32x32" type="image/png">
<link rel="icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/favicon-16.png" sizes="16x16" type="image/png">
<link rel="apple-touch-icon" href="<?php echo esc_url( get_template_directory_uri() ); ?>/apple-touch-icon.png">
<link rel="manifest" href="<?php echo esc_url( get_template_directory_uri() ); ?>/site.webmanifest">
<script>(function(){var d=document.documentElement;d.classList.remove('no-js');try{var t=localStorage.getItem('svls-theme');if(t==='light'||t==='dark'){d.setAttribute('data-theme',t);}}catch(e){}})();</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preload" as="font" type="font/woff2" crossorigin href="https://fonts.gstatic.com/s/intertight/v9/NGSwv5HMAFg6IuGlBNMjxLsH8ag.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin href="https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7.woff2">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@800&display=swap">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/tokens.css?v=c2966ec5">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/site.css?v=d69baeb7">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/pages/contact.css?v=a521a973">
<link rel="stylesheet" href="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/css/theme.css?v=95b1acdc">
<script src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/js/site.js?v=2891427c" defer></script>
<script src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/js/theme.js?v=1aa957a6" defer></script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "ContactPage",
  "name": "Contact SVLS LABS",
  "url": "https://svlslabs.com/contact/",
  "description": "Book a discovery call with an SAP architect, request Value Lens beta access or ask about partner capacity. Replies within one business day.",
  "inLanguage": "en",
  "isPartOf": {
    "@type": "WebSite",
    "name": "SVLS LABS",
    "url": "https://svlslabs.com/"
  },
  "about": {
    "@type": "Organization",
    "name": "SVLS LABS",
    "legalName": "SVLS LABS LLP",
      "telephone": "+91 8500811119",
      "address": {"@type": "PostalAddress", "streetAddress": "4th Floor, Aparna Astute, Shaikpet, Door No. 8-1-299/103&104/AA/4F-2, Jubilee Hills", "addressLocality": "Hyderabad", "postalCode": "500008", "addressRegion": "Telangana", "addressCountry": "IN"},
    "url": "https://svlslabs.com/",
    "foundingDate": "2020",
    "sameAs": ["https://www.linkedin.com/company/svlslabs/"]
  }
}
</script>
<?php };
get_header();
?>
<main id="main">

  <!-- 01 Hero -->
  <section class="hero has-grid hero--plain" aria-labelledby="hero-title">
    <div class="hero-art hero-art--lite" aria-hidden="true">
      <svg class="hero-art__mark" viewBox="0 0 64 64" focusable="false">
        <path d="M4 24V4h20v4H8v16z" fill="currentColor"/>
        <circle cx="32" cy="32" r="13.5" fill="none" stroke="currentColor" stroke-width="5"/>
        <path d="M60 40v20H40v-4h16V40z" fill="var(--svls-accent, #E4432B)"/>
      </svg>
    </div>
    <div class="container">
      <div class="section-mark"><span class="numeral">01</span><p class="eyebrow">Contact</p></div>
      <div class="grid hero__grid">
        <div class="hero__copy col-8">
          <h1 id="hero-title">Talk to an Architect.</h1>
          <p class="lead">Tell us what you are working on. An architect, not a salesperson, replies within one business day with two or three slots or a written answer.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Form (columns 1-7) and the right column (8-12) -->
  <section class="section contact" id="form" aria-labelledby="form-title">
    <div class="container">
      <div class="section-mark"><span class="numeral">02</span><h2 class="eyebrow" id="form-title">Write to Us</h2></div>
      <div class="grid contact__grid">
        <div class="col-7 contact__form" data-reveal>
          <form class="form" method="POST" action="/wp-admin/admin-post.php" name="contact" aria-labelledby="hero-title" data-enhance data-success="Thank you. We reply within one business day. If it is urgent, email service@svlslabs.com." data-subject="Contact enquiry">
            <input type="hidden" name="action" value="svls_form">
            <input type="hidden" name="form-name" value="contact">
            <input type="text" name="_gotcha" tabindex="-1" autocomplete="off" hidden>
            <div class="form__row">
              <div class="field">
                <label class="field__label" for="c-name">Name</label>
                <input class="input" id="c-name" name="name" type="text" autocomplete="name" required>
              </div>
              <div class="field">
                <label class="field__label" for="c-email">Work email</label>
                <input class="input" id="c-email" name="email" type="email" autocomplete="email" required>
              </div>
            </div>
            <div class="field">
              <label class="field__label" for="c-company">Company</label>
              <input class="input" id="c-company" name="company" type="text" autocomplete="organization" required>
            </div>
            <div class="field">
              <label class="field__label" for="c-intent">I am contacting you about</label>
              <div class="select">
                <select class="input" id="c-intent" name="intent" required>
                  <option value="discovery">Discovery call</option>
                  <option value="sap">Discovery call: SAP &amp; ERP</option>
                  <option value="cloud">Discovery call: Cloud</option>
                  <option value="ai">AI readiness call: Agentic &amp; Applied AI</option>
                  <option value="beta">Value Lens beta access</option>
                  <option value="demo">Value Lens demo</option>
                  <option value="suite-demo">SAP Intelligence Suite demo</option>
                  <option value="logicpilot">LogicPilot launch updates</option>
                  <option value="partnership">Partnership: SAP partner capacity</option>
                  <option value="overview">Capability overview PDF</option>
                  <option value="checklist">Governed Agent Control Checklist</option>
                  <option value="checklist-cleancore">Clean Core integration checklist</option>
                  <option value="other">Something else</option>
                </select>
                <svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M1 4l5 5 5-5" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>
              </div>
            </div>
            <fieldset class="fieldset" data-show-when="intent=beta demo">
              <legend>Your role</legend>
              <div class="choices">
                <label class="choice"><input type="radio" name="role" value="finance" data-required><span>Finance</span></label>
                <label class="choice"><input type="radio" name="role" value="sap" data-required><span>SAP</span></label>
                <label class="choice"><input type="radio" name="role" value="it" data-required><span>IT</span></label>
                <label class="choice"><input type="radio" name="role" value="other" data-required><span>Other</span></label>
              </div>
            </fieldset>
            <div class="field">
              <label class="field__label" for="c-message">Message <span class="opt">(optional)</span></label>
              <textarea class="input" id="c-message" name="message" rows="5" placeholder="Landscape, timeline, what good looks like"></textarea>
            </div>
            <div class="form__choices">
              <label class="choice"><input type="checkbox" name="offer" value="two-week"><span>Start with the two-week discovery (fixed scope, fixed price).</span></label>
              <label class="choice"><input type="checkbox" name="notify" value="yes"><span>Notify me when Value Lens leaves beta.</span></label>
            </div>
            <button class="btn btn--primary" type="submit">Send</button>
            <p class="form__privacy">We use your details only to reply to you. See <a href="/privacy/">Privacy</a>.</p>
          </form>
        </div>

        <aside class="col-5 contact__aside aside-rule" aria-label="What happens next, offices and products">
          <div class="contact__block">
            <h3>What happens next</h3>
            <ol class="list-numbered" role="list">
              <li><span class="numeral">01</span><span>We read it the same day.</span></li>
              <li><span class="numeral">02</span><span>An architect replies within one business day.</span></li>
              <li><span class="numeral">03</span><span>A 45-minute call, no deck required.</span></li>
              <li><span class="numeral">04</span><span>If it fits, a two-week discovery proposal with a fixed price.</span></li>
            </ol>
            <p class="contact__link"><a class="arrow-link" href="/approach/">How we run engagements<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></p>
          </div>

          <div class="contact__block">
            <h3>Offices</h3>
            <dl class="offices">
              <div class="offices__row">
                <dt class="mono-title">SVLS LABS LLP</dt>
                <dd>4th Floor, Aparna Astute<br>Shaikpet, Door No. 8-1-299/103&amp;104/AA/4F-2<br>Jubilee Hills, Hyderabad 500008<br>Telangana, India<br><a href="tel:+918500811119">+91&nbsp;8500811119</a></dd>
              </div>
              <div class="offices__row">
                <dt class="mono-title">Email</dt>
                <dd><a class="link" href="mailto:service@svlslabs.com">service@svlslabs.com</a></dd>
              </div>
              <div class="offices__row">
                <dt class="mono-title">LinkedIn</dt>
                <dd><a class="link" href="https://www.linkedin.com/company/svlslabs/" target="_blank" rel="noopener">SVLS LABS company page<span class="visually-hidden"> (opens in a new tab)</span></a></dd>
              </div>
            </dl>
          </div>

          <div class="contact__block">
            <h3>For SAP partners</h3>
            <p class="contact__body">Select Partnership above. NDA-friendly, fixed-scope options.</p>
            <p class="mono-note">NDA-friendly · Fixed-scope options</p>
          </div>

          <div class="contact__block">
            <p class="eyebrow">Products</p>
            <ul class="contact__products" role="list">
              <li><a class="arrow-link" href="/products/value-lens/">Value Lens (private beta)<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></li>
              <li><a class="arrow-link" href="/products/value-lens/#beta">Request beta access<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></li>
              <li><a class="arrow-link" href="/products/sap-intelligence-suite/">SAP Intelligence Suite<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></li>
              <li><a class="arrow-link" href="/contact/?intent=suite-demo">Request a Suite demo<svg viewBox="0 0 12 12" aria-hidden="true" focusable="false"><path d="M0 6h8" fill="none" stroke="currentColor" stroke-width="1.5"/><circle class="arrow-link__pt" cx="9.5" cy="6" r="2.5"/></svg></a></li>
            </ul>
            <p class="status">Value Lens: private beta on synthetic SAP-like data. Production SAP connector in development.</p>
            <p class="status">SAP Intelligence Suite: in use in SVLS LABS delivery. Available to customers on request; deployed in your landscape, reviewed by your architects.</p>
          </div>
        </aside>
      </div>
    </div>
  </section>

</main>
<?php get_footer(); ?>
